//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBL3.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietNguyenLieu
    {
        public int MaNL { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public Nullable<int> SLNhap { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<long> GiaNhap { get; set; }
    
        public virtual NguyenLieu NguyenLieu { get; set; }
    }
}
